# [START app_yaml]
runtime: nodejs18

# service: onzecord

handlers:
  - url: /.*
    secure: always
    script: auto

service: default

env_variables:
  DATABASE_URL: "postgres://default:r8BXsQDbovN3@ep-raspy-smoke-a43k0z3z.us-east-1.aws.neon.tech:5432/verceldb?sslmode=require"
  AUTH_SECRET: "1114f87ef2c3f032a5e2acac1f56fefb98862cad04ee762ae37bc2d923dcd3b9"
  GITHUB_CLIENT_ID: "a9a7ba34ec2457b665ee"
  GITHUB_CLIENT_SECRET: "619df59906549856461e93324feef5c14e1cf176"

# [END app_yaml]