name: "CD Workflow"

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - id: Auth
              uses: google-github-actions/auth@v2
              with:
                credentials_json: ${{ secrets.GCP_SA_KEY }}
                project_id: ${{ secrets.GCP_PROJECT_ID }}

            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v0.4.0
              with:
                project_id: ${{ secrets.GCP_PROJECT_ID }}
                service_account_key: ${{ secrets.GCP_SA_KEY }}

            - name: Deploy
              uses: google-github-actions/deploy-appengine@v0.2.0
              with:
                project_id: ${{ secrets.GCP_PROJECT_ID }}
                credentials: ${{ secrets.GCP_SA_KEY }}