name: "CD Workflow"

on:
    pull_request:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - id: Auth
              uses: google-github-actions/auth@v2
              with:
                credentials_json: ${{ secrets.GCP_SA_KEY }}
                project_id: ${{ secrets.GCP_PROJECT_ID }}

            - name: Deploy to GCP
              run: gcloud app deploy

